#!/bin/bash

help() {
  echo "Usage:"
  echo "  v2fly stop"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  zmicro plugin run compose stop $V2FLY_SERVICE_NAME
}

run() {
  core $@
}

run $@
