version: '3.7'

services:
  ingress:
    restart: always
    build:
      context: ./images/ingress
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    environment:
      UPSTREAM: v2fly:8080
    volumes:
      - ${V2FLY_SSL_DIR}:/etc/nginx-ssl

  v2fly:
    restart: always
    build:
      context: ./images/v2fly
    env_file:
      - $HOME/.v2fly
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
      - /var/log/v2fly:/var/log/v2ray

# networks:
#   default:
#     external: true
#     name: ingress
